### ISSUE TITLE
Error running self provision script on windows

### ISSUE THREAD

**Issue by Samwisebuze** [QuickFixes/web-dev-with-friends#3]
Running `vagrant up` on the host fails spectacularly, and running `/vagrant/bin/self-provision.sh` on the guest gives this error:

```
vagrant@webdev-jessie:~$ /vagrant/bin/self-provision.sh
-bash: /vagrant/bin/self-provision.sh: /bin/bash^M: bad interpreter: No such file or directory
```

The problem was CRLF endings "helpfully" added  by Git, possibly by `core.autocrlf` setting in user's `~/.gitconfig` ([reference](https://help.github.com/articles/dealing-with-line-endings/)).

**Comment by ernstki** [comment]
@Samwisebuze Easiest and cleanest way to test this would be to remove your fork entirely and clone a fresh copy. 

But if you want the practice, you can probably do something like
 
```
cd /place/where/you/cloned/web-dev-with-friends
vagrant destroy  # delete the VM
git add remote upstream https://github.com/QuickFixes/web-dev-with-friends.git
git revert --hard  # WARNING: discards any changes you've made to this repo locally
git pull upstream master
```

Then do `vagrant up` again, and hopefully the provisioning step won't fail this time. Please re-open this issue if you run into any problems.

**Comment by ernstki** [comment]
One other note: if you cloned an earlier version of the repository that was missing the `.gitattributes` (hidden) file, the easiest way to put line endings back to the way they're supposed to be is to delete `*.cmd`, `*.sh` and `bin/*.sh` and then do a `git reset --hard`. (Be careful if you have local changes, though!)

You can find a complete explanation of what's going on here in GitHub's help document called "[Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/)."
